version: "3.7"

services:

  firestore:
    image: pathmotion/firestore-emulator-docker
    # volumes:
    # - firestore-data:/opt/data
    environment:
      FIRESTORE_PROJECT_ID: hafenhause
      FIRESTORE_LISTEN_ADDRESS: 0.0.0.0:8080

  hafenhause:
    image: hafenhause
    environment:
      CORS_ALLOWED_ORIGIN: "*"
      GCLOUD_PROJECT: hafenhause
      PUBLIC_PORT: :8888
      FIRESTORE_EMULATOR_HOST: firestore:8080
      FIRESTORE_PROJECT_ID: hafenhause
    ports:
      - "8888:8888"
    command: /hafenhause
